---
{{- if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: success-share
      interval: 1m
      successCondition: len(result) == 0 || result[0] >= 0.99
      failureLimit: 0
      provider:
        prometheus:
          address: {{ .Values.prometheus.address }}
          query: |
             sum(irate(

            nginx_ingress_controller_nginx_process_requests_total{reporter="source",destination_service="test",response_code!"5.*"}[1m]

           )) / 

           sum(irate(

             nginx_ingress_controller_nginx_process_requests_total{reporter="source",destination_service=~"test"}[1m]

           ))
