replicas: 1
image:
  registry: ghcr.io
  repository: jhandguy/canary-deployment/sample-app
  tag: latest
prometheus:
  enabled: false
  address: http://prometheus-operated.prometheus.svc.cluster.local:9090
