replicas: 1
image:
  repository: argoproj/rollouts-demo
  pullPolicy: Always
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "blue"
prometheus:
  enabled: true
  address: http://prometheus-operated.prometheus.svc.cluster.local:9090
